name: Run Integration Tests
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: .go-version
        cache: true
    - name: Run dev linux build
      run: make dev-linux-only
    - name: Integration Tests
      run: ./scripts/integration_env.sh
